---
- project:
    vars:
      ensure_tox_version: '<4'
    check:
      jobs:
        - openstack-tox-linters
        - k8sapp-oidc-tox-py39
        - k8sapp-oidc-tox-flake8
        - k8sapp-oidc-tox-pylint
        - k8sapp-oidc-tox-metadata
        - k8sapp-oidc-tox-bandit
    gate:
      jobs:
        - openstack-tox-linters
        - k8sapp-oidc-tox-py39
        - k8sapp-oidc-tox-flake8
        - k8sapp-oidc-tox-pylint
        - k8sapp-oidc-tox-metadata
        - k8sapp-oidc-tox-bandit
    post:
      jobs:
        - stx-oidc-auth-armada-app-upload-git-mirror

- job:
    name: k8sapp-oidc-tox-py39
    parent: openstack-tox-py39
    description: |
      Run py39 test for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oidc/*
    vars:
      tox_extra_args: -c python3-k8sapp-oidc/k8sapp_oidc/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'


- job:
    name: k8sapp-oidc-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oidc/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-oidc/k8sapp_oidc/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-oidc-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-oidc/k8sapp_oidc/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-oidc-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oidc/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-oidc/k8sapp_oidc/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-oidc-tox-bandit
    parent: tox
    description: |
      Run bandit test for k8sapp_oidc
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-oidc/*
    vars:
      tox_envlist: bandit
      tox_extra_args: -c python3-k8sapp-oidc/k8sapp_oidc/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-oidc-auth-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/oidc-auth-armada-app to
      github.com/starlingx/oidc-auth-armada-app
    vars:
      git_mirror_repository: starlingx/oidc-auth-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-oidc-auth-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-oidc-auth-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - GC8LPr74Y7meuo+3/NSJB6+9Nk0+tt+OHkzitfToEWlIkrF2j4ze8Pk063h+Vyvk1lYJs
          tR47ZIdzoPzXpDkiihTMAI08C1RaYmlNfO4SA57O1CPR9Or90SOu8pG/QjOybCl2f/o9F
          fDXHv6OcPYA/5rVmMyMmHncJGOmJ47MzOd8Lu1d5Zu91xTuNbiCTsanbYyN7YUtvqThNL
          JDAFnO8rNqogpt6bZa89z16WhXRIU2PwjpK+eziJcsuKGLVFDrII9Tw1UOGcSk7/D3Kks
          DTB7nwLyhyQ56j0a7vXS22/CvYPzFSmrWq/qhpJ6LHaM97sIFWlcC44jmM9yJ/eWpstEg
          k/nrAc9tWAYXS0cEiQ5MdwHVlr18mWsM2YzVK1Z1rksHT+mxIp761JXJAgr5734hDOsYt
          RLzOwoLqqMv5EPkATHh3LY7FbUC2C1nJ8XnywahxjRi0jIZPRNpYicpsDlRtxHpdXnC0y
          ZrIMpL5hOjXjmN7D//Tq5+u6ARyXBWR6vjqz+CM9LPtrZvcs3JlDA88i+Ld0WHBN1AFRI
          F/nP46IIP5gSEPJ7CIhivCRNIg5e9PoFyflWhCbGShUl3B/tezpqnz3Ja4l950kFjulwf
          j4hv9De41QzhB6jr9TjarfjDtlEPcnmws8e4DivOJRrswcs9Dq0H7KQkrjq3Zs=
        - YXNth6suDe1DEzbxwWoKVbu4nBsEhgl9pipy8Hkw2AdHDWmLADjNTy8WNYM5DBNLM4UFM
          8aOK3tjM7HOSQ+4hPGISFT8CJS/bE4Zf93KI3REfdjTODvxTBHbmIZy9dUQKjfCBv7hXl
          suozJfH1RkxfLB4tgkY/5RgueGZEV2hefzSXHLVz7egsoMea6byVBSgsl9VG6sUuQe4kV
          lusD0V79HawMswK0QOLZ8tlKaJ62jBOnQhroNNwPQUpriAGPnzyyEobF+5G71OJO522nc
          YAxkCLA5xW+lFsDBm3zxrtBlT4wBlAudfsRO+AOAHmlk7pfbOz985iIq3zM+sSgdrcOE6
          mwvCBeFXjketILvv2z2NQZllk/xo6IYHOw9+HZ5Uxs/83stsXc8YIzL3uqlPtAu2Yaria
          JGg/FQZfCxILefNYU9VrjUQoLYPWN3jQN2CfKE5pEXA12L/I3sT91wUgMr+uHqqdjnS3w
          HfMWPLEqY3I12bRo/4ycFMiORGEQvKYFSuDxzj8jOQWcZl6BlNK+ir96LNf4lE1PKTQOY
          akMV8hi+OQepW9vMkV+gA8z8KVDhkiGIl9AQ/DZkT85COMkGI3W+QqC7ah+IYlV6GulZd
          1VAhe8ptM2P6JAYXwu4FbVDBIkeEUPOjSs/RvaIvv0CWHLxa2Adrph/V2IdSmM=
        - E7RPDB34xwjG48qROxAkwmCqjniwxAfyNPcQHMTEO/Ugp4q2pmzHxAV0dplAbNLOOuaxl
          FGZoCnVCJuH9TtR4suu2rddQ3nnD6Ycr0dw7Hd84hXSXKK4gRfVVFktMU4/IAVAIUHsTB
          OQcTegZ5lixIsYunaayG6EbRWgLfuYiRLHiVezrB+xp3M8q0eprpAxDkdKnsgRiqcDjDc
          BeC0FrcuVKKnVOZ0zg8BnZqyOFWD7a8/qjGNmc3zXnpwTisFzkmoC3GAwVCogUBBs6FmD
          vSj+dZVfql3yvi18RYon4nA4nGGFCmQ0srEbXh/wZdH+C5iPfV32IJdM3ZVJkVQ4gdsWP
          +5/V0msaR2PHAIF6fXnVII3yjjk9kysbOlqQWpiJrZuprJ7c+KP1esEW3jWTxCkHuDAFt
          IYSp1jRiD10fGRzwjrRI5+nQkwCGqtMBw8s5cxyN09M6Y1GbDSrlS5uFtz1Q13TumNNxN
          MNLG4PKpevd4gE+HVKPtPYbB+nWSoi0pwYo9bqzM3ktFMzrlru8Q+4d/mdeUxsgdw1/p4
          XYkpH32t0dZh0pGIHbcOmn2+sqPsP3feevmhLCiVtCVA00vakOYNri7MSU++IcM5lBJeX
          A9h2E1FOXyC78bpnVtdoj2fLEMSU9eYNYsvn+X1flTn4SOuzwbbf+gr14ivcMg=
        - Y5/+cvc/eOUsskPM4YNNMAFYLM8jMWecz/TJLdwUsXgGhBuHoXMy0aRNZ8dkRcrjikPzK
          re5iZHA73pOVvKdyynNkp3OB3B2Mra7C3TZgFLeWFFy8i4Fr7ptKbUNin6HayifyjeG2g
          4KTtVKW0jyEjffaKJr/ZRrEVmPC0Lt6EinXGnyiB/OibPKeNCWvS9D/Vc+x2a0lLmmy+s
          mby5Ho+GyegsWJA18Ue2n8QBhEgK3kNDJ7qAT5AF3mJMZ2UjrEWsZGkMEUxuNf16k2obW
          dZ3CIXS6g9HW+6jsV+xHc+0oPxxQVL8HrFKW9clGQmdgdM06hF7bzeT8Sup7jdgRcHFjF
          DKV8rFSTc/kVhTn13uUJ0n6SCd1WMh08KqrUq/KLSxUvVAwjmUaGW6T5J0nq4wKmAzClA
          +n8D4tOI9MZHwBEfGVHFos4x7tpwVtv8zjlwx1t8ekMnDmAPw9NZ5HUN5j0NUHqoUHAuH
          khSIK/fV4os1EOYHcveroYhlVcsUBxfyVD3GynC0zT92bhg+AzBPyg2r2fcrSZJI/93Ma
          vxEMRbS2+X/M2rU6nX9UBhDGBNvYMNhPjE7EKddDXlV6tF+kY3HktSWB288Z5kAOgaqTp
          D5UQndx1zFMr4sIHwZ73vdRvn+1qw8qJbIiy9hFQejAk7Rb21SzzBo+6o5p2/I=
        - P4rfKgZLRYOJz5wT+U/fynXQtpAwtxTtOpojdE+CnNFT9KM74D1d1zHlWDLgj/wBdpCtZ
          ssvenL7PPUM9dR1kar3nX2joe3JsXQWTHlz/O3As+QZ7+oBpeCQxA5WeKCsqZt6Q/JQAm
          gN00J4qW+JWuyrIVt+8zJsHU4BLdM2WBlmtdCMiUmBban5mdr2FAlz+ynIoq0y8BUa7tT
          PkK1FSZC4L316Pi4c8xZUDKzCINiHNjUNUOSmMgU16fMV+cL91O7+HEi+DioLaEu158nj
          SZEuLM9SGYIweF3bF5R7z0OGt+kfjyg5gM+QOehtNw+WCPzUjZ/34w6rSgLs2DTzF/60f
          N7UPmAnyGIXl0pFJnKX48fP4+qWVj3J2Ot690tAZJimeFTh10fECrQlfzYd1wv4KojP5O
          RXWO+lk29tvSgaHVaeGEJpt9TdnkHFwv29jGqAu2/aM4zqtyn4hsNa4+sVe8CW6x/j0AN
          20+1OvHX23mPDezzVTllJ6xBZKq4saBAzoKpK0EOmEQpiJSI60OBEZWDE9ihm/vU72kJs
          lX9O8YfZIyslvtIKCYzP27jQdQmYtVDYoG7KHWFlz8Cl/Edl4TR0IVOob6HXoMqKJkNAe
          hWWTzkkViSIG+lAjnysa9IVF65cKii1KmddE/tzYhklvqgytO3LzGOU/4APCJ4=
        - hiCq+GTVTRcDiZ4Fub6Q/4EWI1Rpq1NiS4RWgJOxSPwRmla82HdioVA76t3NHDrkKkIa6
          0Apf4x1KeFGqWc3wqZRiOfdZ8lfgR9VZYmcWHnogbIuamVFVyGbQCEV4bM2QZNLES5+7Q
          79WamQX5Z3B0hUUDEnfO93Q+D0rXPvpZo/9emO/Y3D8n5DZmQ6pCt3tm5zOl0aSuSRdK3
          JW5cBSIBnB5Xt4bAks4hkNut9mzuoxyAkTQ50JPq25PuuPSkk1hdniMBf+K3JC4TpYVLG
          AeclMYY+vqkIEiqVvawozSf9G9oLJzfv4qu49D2wGh3NXHDNf31wvZ4jD5j75cfvtQIMg
          bFmYHvt1PncaJY9j18AFtkbDVve40lCB5IDHbmIXZgReOffkcdGhKIqvWQDp/mL1E7Dgc
          NDzs1sJJETtknnx79xVV5n+mgZQ0tR2cnnCpUmfrSSFtl9lDJORF+yzd8d93AsHRel6lZ
          Q6+1mIVy47T7gpENtjeIzZ/rlhQBfcYG15n5FSllzEliavBH0stErtoE/LCxa3ENzdvMj
          kHpG1mDE6CbBiieTz+ZlqGpByRUxZwUt3PGMYw4MUazH946hUiANBOdGViR32r+RDldRt
          Urjo/C9t2FSKdkq7VqQrN0Bu8RQkm9B7NGPmfGbF0oRG9TSzAsU3fG9Nkvsk20=
        - H4+Ezpd+fTTuxejkKdVKGJMoZrqBs2g27uXjX7R2kZTSkGzQrVsuA1m7WX1Q+bTuqVY/F
          8tZNXNZEUjdOVUaofPFuQk51RrZu/2pbj0fzgIJyxwpKblVEC1KLPMDfNYqA+I3RsnLUj
          7x320p7qCUE8IiQQwHe+RLBp/9DS7f2Swe8tGfz8CyL7sgNqDVxgF/GZ2npl4O8R25cYZ
          pPIXPgsYWU0/dliYlauo7C/idSN3ULBVZHGcJi1/+nmSlrl/YANNBS35IW7B06ddqiehG
          QIrf9qY60684+4FU+8PLA1gaLk7G+b/04FBeX22HxUbXoeRHfXe9E8ynLtHQTOuIke4em
          q+zshguSf0AR9KnsQVSoqbOHW7coOltNo6QdDK66XvCI7FMORlORRsWruCej27l0dsxH9
          N4mQcP26rXf9vVCZElCoekcpws3G3BbML8yvJUEiAo6Ha+9htJj5gET1iokowtsNVrL9q
          mUy8NcGC99YGaNrVY5RpftKlFdWmUtHuu57szgv/s6zWVkUave2ksprha88cot8GakK/U
          s45UzXlhh+4trCUCRrh4NhZ8IUo0zr3Ht6DGrNfhiHUMo0Y75QorgMZte68A4e31Tvr1Z
          k9MeNBvAXQqxM5Df5i04J5UbFgvTdrMv74iS7o26QFl13Y3bLcBCp7B2rZJAcc=
