{{/*
#
# Copyright (c) 2020 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stx-oidc-client
  labels:
    app: stx-oidc-client
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: stx-oidc-client
  template:
    metadata:
      labels:
        app: stx-oidc-client
      annotations: {
        configchecksum: {{ toYaml .Values.config | sha256sum | trunc 63 }}
        }
    spec:
      imagePullSecrets:
        - name: default-registry-key
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["./stx-oidc-client"]
          args: ["--config", "/etc/dex/cfg/config.yaml", "--debug"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpPath }}
              port: 5555
              scheme: HTTPS
              initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
              timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
              failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpPath }}
              port: 5555
              scheme: HTTPS
              initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
              periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
              timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
              failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/home"
              name: dex-client-secret-volume
            - mountPath: /etc/dex/tls/https/server
              name: https-tls
            - name: config
              mountPath: /etc/dex/cfg
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: dex-client-secret-volume
          secret:
            secretName: dex-client-secret
        - name: https-tls
          secret:
            secretName: {{ .Values.tlsName }}
        - name: config
          configMap:
            name: stx-oidc-client
