#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: dex
  labels:
    chart_group: starlingx-dex-charts
spec:
  releaseName: oidc-dex
  chart:
    spec:
      chart: dex
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: dex-static-overrides
      valuesKey: dex-static-overrides.yaml
    - kind: Secret
      name: dex-system-overrides
      valuesKey: dex-system-overrides.yaml
