#!/bin/bash
set -x

PKG_BUILD_NAME=$1
PKG_BUILD_ROOT=$(realpath `pwd`/${PKG_BUILD_NAME})
PKG_DIR="stx-oidc-auth-helm"

STX_BASE=$(realpath ${MY_REPO}/stx)
SRC=$(realpath ${STX_BASE}/oidc-auth-armada-app/${PKG_DIR}/${PKG_DIR})
SECRET_HELM_CHARTS=$(realpath ${STX_BASE}/helm-charts/secret-observer/secret-observer/helm-charts)

mkdir -p ${PKG_BUILD_ROOT}

# Copy PSP rolebinding helm charts to the build directory.
cp -pr ${SECRET_HELM_CHARTS} ${PKG_BUILD_ROOT}
cp -pr ${SRC}/files ${PKG_BUILD_ROOT}
cp -pr ${SRC}/helm-charts/* ${PKG_BUILD_ROOT}/helm-charts
cp -pr ${SRC}/manifests ${PKG_BUILD_ROOT}
