#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: HelmRelease
metadata:
  name: oidc-client
  labels:
    chart_group: starlingx-dex-charts
spec:
  releaseName: oidc-oidc-client
  chart:
    spec:
      chart: oidc-client
      version: REPLACE_HELM_CHART_VERSION
      sourceRef:
        kind: HelmRepository
        name: stx-platform-oidc
  dependsOn:
    - name: dex
      namespace: kube-system
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: oidc-client-static-overrides
      valuesKey: oidc-client-static-overrides.yaml
    - kind: Secret
      name: oidc-client-system-overrides
      valuesKey: oidc-client-system-overrides.yaml
