{{/*
#
# Copyright (c) 2020 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: stx-oidc-client
  labels:
    app: stx-oidc-client
data:
  config.yaml: |-
    {{- with .Values.config }}
{{ toYaml . | indent 4 }}
    {{- end }}
