#
# Copyright (c) 2022-2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: secret-observer
  labels:
    chart_group: starlingx-dex-charts
spec:
  releaseName: oidc-auth-secret-observer
  chart:
    spec:
      chart: secret-observer
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: secret-observer-static-overrides
      valuesKey: secret-observer-static-overrides.yaml
    - kind: Secret
      name: secret-observer-system-overrides
      valuesKey: secret-observer-system-overrides.yaml
