#
# Copyright (c) 2020-2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# Default values for stx-oidc-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

tlsName: local-dex.tls

image:
  repository: docker.io/starlingx/stx-oidc-client
  tag: stx.11.0-v1.0.9
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 5555
  nodePort: 30555

config:
  client_id: stx-oidc-client-app
  client_secret: St8rlingX
  issuer: https://10.10.10.3:30556/dex
  issuer_root_ca: /home/dex-ca.pem
  issuer_root_ca_secret: dex-client-secret
  listen: https://0.0.0.0:5555
  redirect_uri: https://10.10.10.3:30555/callback

# Default probe configs
livenessProbe:
  initialDelaySeconds: 1
  failureThreshold: 1
  httpPath: "/healthz"
  periodSeconds: 10
  timeoutSeconds: 1

readinessProbe:
  initialDelaySeconds: 1
  failureThreshold: 1
  httpPath: "/healthz"
  periodSeconds: 10
  timeoutSeconds: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

helmv3Compatible: false
